name: yuzu-clang

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Fetch submodules
      run: git submodule update --init --recursive

    - name: yuzu-clang.sh
      run: chmod a+x ./yuzu-clang.sh && ./yuzu-clang.sh
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
       name: yuzu
       path: /home/runner/yuzu-mainline/build/yuzu-x86_64.AppImage
